[build]
  command = "npx sass scss/index.scss:css/index.css scss/hub.scss:css/hub.css scss/chapitre.scss:css/chapitre.css scss/categorie.scss:css/categorie.css scss/communaute.scss:css/communaute.css scss/legal.scss:css/legal.css scss/profil.scss:css/profil.css scss/recherche.scss:css/recherche.css --no-source-map"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
